## **Common Ternms**


# 📘 1. Corpus
**🔹 Easy Meaning:**
A corpus is a big collection of texts (many documents or messages).
Think of it like a folder full of files you want to study or train a model on.

**🧠 Example:**

A folder with 1,000 emails = Corpus

A collection of tweets = Corpus

# 📝 2. Vocabulary
**🔹 Easy Meaning:**
Vocabulary is the list of unique words found in your corpus.
It shows what words are used, not how often.

**🧠 Example:**
If your texts have:

“I love NLP”, “NLP is fun”, “I love Python”

Vocabulary = {I, love, NLP, is, fun, Python}

✅ No repeats — just the full word list.



# 📄 3. Document
**🔹 Easy Meaning:**
A document is one piece of text inside your corpus.

**🧠 Example:**
If the corpus is 1,000 emails,
then each email = one document.

**Another example:**

One tweet

One review

One paragraph
All are “documents”.

# 🔤 4. Word
**🔹 Easy Meaning:**
Just a single word in a document.

**🧠 Example:**
In the sentence “I love Python”,
the words are: I, love, Python

---

# **Important NLP Feature Extraction Techniques**

## **1. One-Hot Encoding (OHE)**  
**🔹 Easy Meaning:**  
Turn each word into a vector (a row of 0s and 1s) where only one word is 1, and all others are 0.  

**🧠 Example:**  
Let’s say vocabulary = ["cat", "dog", "fish"]  

- "cat" → [1, 0, 0]  
- "dog" → [0, 1, 0]  
- "fish" → [0, 0, 1]  

✅ Simple but inefficient for large vocabularies.  

---

## **🧺 2. BoW (Bag of Words)**  
**🔹 Easy Meaning:**  
Counts how many times each word appears in the sentence or document.  

**🧠 Example:**  
**Sentences:**  
1. "I love NLP"  
2. "I love Python and NLP"  

**Vocabulary** = [I, love, NLP, Python, and]  

**Now count how many times each word appears:**  

![Bag of Words Example](Bag%20of%20Words%20Example.png)  

✅ Good for basic text analysis and ML models.  


**✅ Advantages:**

Simple to understand and implement – great for beginners.

Works well with traditional machine learning models.

Fast to compute with small vocabulary sizes.

Gives a solid baseline for text classification tasks.

**❌ Disadvantages:**

Ignores word order, so it loses meaning (e.g., "not happy" vs "happy").

Vocabulary can become very large, especially with big datasets.

Sparse vectors (many zeros) use a lot of memory.

Does not capture context or relationships between words.

In [4]:
# Bag of Words (BoW)


import numpy as np
import pandas as pd

# Create a DataFrame with text data and output labels
df = pd.DataFrame({
    'text': [
        'people watch campusx',
        'campusx watch campusx',
        'people write comment',
        'campusx write comment'
    ],
    'output': [1, 1, 0, 0]
})

# Display the DataFrame
print(df)


                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0


In [5]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
cv = CountVectorizer()

# Create the Bag-of-Words representation
bow = cv.fit_transform(df['text'])

# To see the vocabulary and the actual matrix, you could add:
print("\nVocabulary:", cv.get_feature_names_out())

print("Bag-of-Words matrix:\n", bow.toarray())


Vocabulary: ['campusx' 'comment' 'people' 'watch' 'write']
Bag-of-Words matrix:
 [[1 0 1 1 0]
 [2 0 0 1 0]
 [0 1 1 0 1]
 [1 1 0 0 1]]


---

## **📦 3. N-gram**  
**🔹 Easy Meaning:**  
It means combining N words together to understand context.  

**🧠 Examples:**  
- **Unigram (1 word):** ["I", "love", "NLP"]  
- **Bigram (2 words):** ["I love", "love NLP"]  
- **Trigram (3 words):** ["I love NLP"]  

✅ Helps machine understand phrases, not just single words.  

---

In [12]:
import numpy as np
import pandas as pd

# Create a DataFrame with text data and output labels
df = pd.DataFrame({
    'text': [
        'people watch campusx',
        'campusx watch campusx',
        'people write comment',
        'campusx write comment'
    ],
    'output': [1, 1, 0, 0]
})

# Display the DataFrame
print(df)

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0


In [16]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

# Create the Bag-of-Words representation
bow = cv.fit_transform(df['text'])

In [20]:
# vocab
print(cv.vocabulary_)
print("Length = ",len(cv.vocabulary_))

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}
Length =  6


In [15]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]


# **🤔 Why move from N-gram to TF-IDF?**

**🔹 First, understand what N-gram does:**

It joins N words together to capture short phrases.

**For example:**

**Bigram:** "I love" or "love NLP"  
**Trigram:** "I love NLP"

✅ It’s better than just counting single words because it starts to understand context (phrases).

---

### ❌ But N-gram has some problems:

---

| ❌ Problem               | 📖 What it means                                                                 |
|-------------------------|----------------------------------------------------------------------------------|
| **Too many combinations** | More words = more N-grams = bigger feature space (high memory usage)             |
| **Still just counting**   | It doesn't know which words are important — all words/phrases are treated equally |
| **Common words dominate** | Common words like "the", "and", "is" appear a lot — but don't add much meaning   |

---

# ✅ So, we move to **TF-IDF** (Term Frequency – Inverse Document Frequency)

### 🔹 Easy Meaning:

> “If a word appears a lot in **one document** but not much in others, it’s probably important.”

TF-IDF gives **higher weight** to important words and **lowers weight** for common words.

---

### ⚖️ N-gram vs TF-IDF

| Feature               | N-gram            | TF-IDF                         |
|-----------------------|-------------------|--------------------------------|
| Understand phrases?   | ✅ Yes             | ✅ Yes (when combined with N-gram) |
| Weigh word importance?| ❌ No              | ✅ Yes                          |
| Handles common words? | ❌ No              | ✅ Yes (reduces their weight)   |
| Feature size          | 📈 Very Large      | 📉 Smaller & more meaningful    |

---

### 🧠 In Simple Words:

- Use **N-gram** to capture phrases.
- But use **TF-IDF** to make the model **focus on important words**, not just frequent ones.

> 👉 Best of both worlds:  
> Use `TfidfVectorizer(ngram_range=(1,2))` for **weighted n-grams**.


---


# **📚 What is TF-IDF?**
**TF-IDF stands for:**

👉 Term Frequency – Inverse Document Frequency

It’s a method to score words based on how important they are in a document compared to other documents.

---

## **🔹 Easy Meaning:**

- **TF** = How often the word appears in one document  
- **IDF** = How rare that word is across all documents

---

## **🧠 Think like this:**

- If a word appears many times in one document, it's probably important (TF).
- But if that same word appears in every document, it's probably not special (IDF).

✅ So TF-IDF helps us find the **important and unique words** in each document.

---

## **📦 Example:**

Imagine we have 3 sentences (documents):

1. "I love NLP"  
2. "NLP is fun"  
3. "I love Python and NLP"

**Now:**
- The word **"NLP"** appears in all 3 documents → common → **lower IDF**
- The word **"Python"** appears only once → rare → **higher IDF**

🔸 So, TF-IDF gives:
- **Lower score** to common words (like "NLP")
- **Higher score** to rare/unique words (like "Python")

---

# 📸 TF-IDF Diagram 1 (Formula + Table View):

![TF-IDF Diagram](TF-IDF%20Diagram.png)

---

## 🎯 Why use TF-IDF?

| ❌ Without TF-IDF (just count) | ✅ With TF-IDF                    |
|-------------------------------|----------------------------------|
| All words treated equally     | Important words get higher scores |
| Common words dominate         | Rare but meaningful words stand out |
| No sense of word importance   | Smarter and more focused features  |

---

## 🧪 Simple Formula :

**TF-IDF = TF × IDF**

TF = (Word Count in Document)

IDF = log(Total Documents / Documents containing the word)



In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF Vectorizer
tfidf = TfidfVectorizer()

# Fit and transform the text data to TF-IDF features
tfidf_matrix = tfidf.fit_transform(df['text']).toarray()

# Display the TF-IDF matrix
print("TF-IDF Matrix:")
print(tfidf_matrix)

# Display feature names (vocabulary)
print("\nFeature Names (Vocabulary):")
print(tfidf.get_feature_names_out())

TF-IDF Matrix:
[[0.49681612 0.         0.61366674 0.61366674 0.        ]
 [0.8508161  0.         0.         0.52546357 0.        ]
 [0.         0.57735027 0.57735027 0.         0.57735027]
 [0.49681612 0.61366674 0.         0.         0.61366674]]

Feature Names (Vocabulary):
['campusx' 'comment' 'people' 'watch' 'write']


---

## **✍️ 4. Custom Features**  
**🔹 Easy Meaning:**  
You create your own features from the text — based on your logic or goals.  

**🧠 Example:**  
From this review: *"I LOVED the movie!!! 😍"*  
You can create custom features like:  
- Number of uppercase words → **1**  
- Has emojis → **Yes**  
- Contains “loved” → **Yes**  
- Word count → **5**  

✅ You choose what matters most. Great for ML models.  

---

## **🧠 5. Word2Vec**  
**🔹 Easy Meaning:**  
Converts each word into a vector (set of numbers) that shows the meaning of the word, not just the word itself.  

**🧠 Example:**  
- Word2Vec("king") → [0.12, 0.65, -0.33, …]  
- Word2Vec("queen") → [0.14, 0.68, -0.30, …]  

And guess what?  
**king - man + woman ≈ queen**  

✅ Word2Vec understands meaning and context (semantic similarity).  
Much better than BoW or OHE for deep NLP work.  

---

## **📊 Summary of important NLP feature extraction techniques**  
![Summary](<Summary important NLP feature extraction techniques.png>)


